<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
			.output{
				width: 80%;
				margin: 0 auto;
				text-align: initial;
			}
        </style>
    </head>
    <body>
        <h3>Data from server:</h3>
		<?php if (isset($data)) : ?>
			<div class="output"><?php echo json_encode($data, JSON_UNESCAPED_UNICODE); endif;?></div>
    </body>
</html>
