<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
			table{
				margin: auto;
				text-align: start;
			}
			table, td {
				padding-right: 20px;
			}
			.main_row { 
				color: #a9bd93;
				font-weight: bold;
			}
        </style>
    </head>
    <body>
        <h1>Slim</h1>
        <div>a microframework for PHP</div>

        <?php if (isset($name) && $name === "api") { ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
				<h3>The full list of methods:</h3>
				<table>
				<tr class="main_row">
					<td>URL</td><td>HTTP Method</td><td>Operation</td>
				</tr>
				<tr>
					<td>/api/items</td><td>GET</td><td>Returns an array of items</td>
				</tr>
				<tr>
					<td>/api/categories</td><td>GET</td><td>Returns an array of categories</td>
				</tr>
				<tr>
					<td>/api/items/[number]</td><td>GET</td><td>Returns an item with id=number</td>
				</tr>
				</table>
		<?php } else { ?>
			
            <p>Try <a href="api">API</a></p>
        <?php } ?>
    </body>
</html>
